### ISSUE TITLE
Breaks on sites that don't allow admin changes

### ISSUE THREAD

**Issue by andypullen** [alpshq/craft-share-previews#7]
When the Craft config is set to `"allowAdminChanges" => false` on a server environment, there is no way to access Share Preview's settings or complete the plugin setup wizard.

```
yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in /var/www/craft/vendor/craftcms/cms/src/services/ProjectConfig.php:493
Stack trace:
#0 /var/www/craft/vendor/craftcms/cms/src/services/Plugins.php(739): craft\services\ProjectConfig->set()
#1 /var/www/craft/vendor/alpshq/craft-share-previews/src/controllers/SetUpController.php(107): craft\services\Plugins->savePluginSettings()
#2 /var/www/craft/vendor/alpshq/craft-share-previews/src/controllers/SetUpController.php(144): alps\sharepreviews\controllers\SetUpController->saveSettings()
#3 /var/www/craft/vendor/alpshq/craft-share-previews/src/controllers/SetUpController.php(33): alps\sharepreviews\controllers\SetUpController->hideSetUpNavigationItem()
#4 [internal function]: alps\sharepreviews\controllers\SetUpController->actionPost()
#5 /var/www/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#6 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#7 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#8 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#9 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction()
#10 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest()
#11 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#12 /var/www/craft/web/index.php(21): yii\base\Application->run()
#13 {main}
```

**Comment by andypullen** [comment]
I spoke too soon and didn't realize that the plugin settings are included in project.yaml. My bad!

**Comment by jakubjo** [comment]
No worries, @andypullen!
